name: 'Bump Action'
description: 'Bump a version based on commit message, tag it, and push package.json update to repository'
inputs:
  github_token: 
    description: 'github access token'
    required: true
  src: 
    description: 'source code dir/file to compile'
    required: true
  branch:  
    description: 'the destination branch'
    default: 'master'
outputs:
  dist: # output will be available to future steps 
    description: 'The dist folder'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'  
  color: 'red'
