name: 'ncc action'
description: 'use @zeit/ncc to compile and push your github action's dist directory! 🚀'
author: 'Tal Hayut'
inputs:
  github_token: 
    description: 'github access token'
    required: true
  src: 
    description: 'source code dir/file to compile'
    required: true
  branch:  
    description: 'the destination branch'
    default: 'master'
  commit_msg:  
    description: 'commit message used when pushing dist'
    default: 'dist release 📦'
  ncc_args:
    description: 'command seperated args for ncc'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'pink'
