name: ncc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/ncc@debug
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'index.js'
        branch: 'debug'