name: ncc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/ncc@no_run
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'index.js'
        branch: 'no_run'